fieldLayouts:
  44d8c561-04c1-4975-83bb-3dd3231634f9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c152a04f-07db-43bf-b431-391b600ec457
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cacc11c5-9f61-4276-94ab-ccbd9ddb6509 # Titre
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb412ed3-f0da-44ae-8cfd-f2cd977b2e38
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 035f016c-0caf-42b2-8120-b6ad94c7b445 # Texte
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b18c63c4-ff7e-4a19-a46e-6f621bfc1edb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee5544e3-9a58-4e7f-8a6b-8139a835c792 # Lien
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab36edb3-a06a-423c-b02d-2ef5258f5618
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 96a999df-e7b2-4cb2-bd93-23423e4f4b48
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: b59406eb-ba12-466d-8011-e4dd57826da5 # Appel à l'action
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
