dateModified: 1740774884
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - link
      type: native
    -
      key: singles
      type: native
email:
  fromEmail: $EMAIL_SYSTEM_ADDRESS
  fromName: $EMAIL_SENDER_NAME
  replyToEmail: $EMAIL_REPLY_TO
  template: null
  transportSettings:
    host: $EMAIL_HOSTNAME
    password: $EMAIL_PASSWORD
    port: $EMAIL_PORT
    useAuthentication: '1'
    username: $EMAIL_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  fileSystemsAssetTransforms:
    hasUrls: true
    name: 'Asset transforms'
    settings:
      path: '@webroot/asset-transforms'
    type: craft\fs\Local
    url: '@web/asset-transforms'
  fileSystemsDocuments:
    hasUrls: true
    name: Documents
    settings:
      addSubfolderToRootUrl: true
      autoFocalPoint: false
      bucket: $S3_BUCKET_DOCS
      bucketSelectionMode: manual
      cfDistributionId: $S3_DOCS_DIST_ID
      cfPrefix: $S3_BUCKET_SUBFOLDER
      expires: '1 years'
      keyId: $S3_USER_ID
      makeUploadsPublic: false
      region: $S3_BUCKET_REGION
      secret: $S3_USER_SECRET
      storageClass: ''
      subfolder: $S3_BUCKET_SUBFOLDER
    type: craft\awss3\Fs
    url: $S3_DOCS_URL
  fileSystemsImages:
    hasUrls: true
    name: Images
    settings:
      addSubfolderToRootUrl: true
      autoFocalPoint: false
      bucket: $S3_BUCKET_IMAGES
      bucketSelectionMode: manual
      cfDistributionId: ''
      cfPrefix: ''
      expires: '1 years'
      keyId: $S3_USER_ID
      makeUploadsPublic: false
      region: $S3_BUCKET_REGION
      secret: $S3_USER_SECRET
      storageClass: ''
      subfolder: $S3_BUCKET_SUBFOLDER
    type: craft\awss3\Fs
    url: $S3_IMAGES_URL
meta:
  __names__:
    0b4a098d-aaae-4c9b-ae9d-927d1e93d0a5: Vidéo # Vidéo
    0dd609b9-f4c9-47f4-81d6-b7f511c392fb: Image # Image
    1e66bcbd-1f21-4f4f-a59f-a3c5a6dbcd86: 'Documents et liens utiles' # Documents et liens utiles
    02ba1ea7-8030-4c73-b881-115d72707a13: Lien # Lien
    2c23fcd1-12ca-44be-8682-91de03c0087d: Image # Image
    4e72d0d2-9132-4c33-aa32-0bd73e9e0356: shared # shared
    5c507ccd-fdc2-4130-9edc-bab438b52239: 'Galerie d''images' # Galerie d'images
    5dcd6757-f6c7-4096-b458-69e19b062435: Default # Default
    5e26c56c-3d58-4913-8710-34778b34efb0: Documents # Documents
    6a04471f-3fc2-49a7-9b39-74470207706a: Titre # Titre
    7c59b4df-d6a7-4142-8a30-ff2a727fa217: 'Appel à l''action' # Appel à l'action
    7d923ca0-fc68-4351-98ec-1274de3906db: Accueil # Accueil
    8b634c53-c6af-4a69-a469-17c41e2b40b0: Anglais # Anglais
    8d996f70-342d-475d-aa7d-27cba0799d23: Lien # Lien
    9b18697d-2ce6-492b-b628-1a649bb22eaa: 'SEO Open Graph Image' # SEO Open Graph Image
    09e92af8-6d6e-4000-a57a-4155049cb4cc: globalSettings # globalSettings
    25f098f1-949b-4cb2-bd3f-036653354b1f: 'Éditeur de texte' # Éditeur de texte
    035f016c-0caf-42b2-8120-b6ad94c7b445: Texte # Texte
    46e7ba4d-9425-49ca-9b1b-4c1be930faa4: 'Réglages généraux' # Réglages généraux
    50ce685f-118b-4141-b6d1-5282a13c9356: Titre # Titre
    64e6a8c5-2657-430e-b507-e15764d40233: Texte # Texte
    80e7bc64-a66a-42dd-b8a5-da4e1d3f4f1f: Légende # Légende
    88de4ae9-1a9a-433f-a426-4c32e55af0c0: Texte # Texte
    96dfd863-7ae3-46ef-9af8-2832cd03d9f5: Texte # Texte
    99e645b0-0958-419c-91ae-2d09f1e2c385: Images # Images
    101e30c3-c003-4c0e-8d02-fc879046fb06: Default # Default
    191fb529-463a-46f3-9a43-5784187f08dc: Lien # Lien
    228f18ac-b71c-4021-8f66-0d34f29a880f: 'SEO global' # SEO global
    0499bd9f-6aa1-4590-9c16-e86191e0a2b8: Accueil # Accueil
    508c17b2-93a7-492f-8f5f-3aedcc6e0228: Pages # Pages
    698fcc28-8a7f-41ad-a04d-2b690ff4d9c2: Liens # Liens
    979c6314-836d-4d38-b227-00d1ed756969: 'Appel à l''action' # Appel à l'action
    2133a69a-1d77-4a0e-b10c-84a0ade4445d: Source # Source
    06296f60-f990-4c10-a3b8-b904d544672d: Image # Image
    8820f305-2c5c-4d89-8a31-52d907243495: Texte # Texte
    34253b52-db56-4c20-876d-a31f42b59161: Titre # Titre
    40506d4b-37d0-431a-957b-6712f9613a10: Titre # Titre
    067993aa-db2d-4342-8694-0e474f184c6d: Lien # Lien
    140379d6-15ce-4188-851c-d2625b19a5e9: Image # Image
    00548086-7b2f-44f0-a0e4-c9d91fcaae9e: Images # Images
    1352064c-7bb0-4304-bf1f-20ca42de9f97: Image # Image
    81304912-0d5b-4feb-9926-1e423206864e: Assets # Assets
    a7870a18-8ec8-42bd-bb94-ea232c8eb066: SEO # SEO
    ab29d8d4-e2ba-446a-8841-f53efeede83b: Vidéo # Vidéo
    b4a35b8a-1eff-4137-817a-17e468158aed: 'Public Schema' # Public Schema
    b59406eb-ba12-466d-8011-e4dd57826da5: 'Appel à l''action' # Appel à l'action
    bbed9d5a-e7a4-48f4-afeb-0d2faa845218: 'Transformer en accordéon' # Transformer en accordéon
    c1436119-37a0-4b5b-9538-52c47b611fd2: $SITE_GROUP # $SITE_GROUP
    ca2a274d-ce21-46a0-81e5-cd4dba43a25a: Documents # Documents
    cacc11c5-9f61-4276-94ab-ccbd9ddb6509: Titre # Titre
    d0165c69-1525-4ee1-ac0e-55161683611a: Image # Image
    d5dc88b0-753d-465b-8f25-a2a3081f2fed: 'Texte - Image' # Texte - Image
    d8aa590c-b90d-475a-a912-7e992e1f847e: Titre # Titre
    d2250f74-fb1f-40a1-b18b-496b290fa7ec: Position # Position
    d75846a9-8f9c-4c04-88c3-edb6be38cb7c: 'Transformer en accordéon' # Transformer en accordéon
    d3974314-8390-48bd-af85-f938616558be: 'SEO Description' # SEO Description
    dc3bf0d7-587d-4f8a-bf3b-9ab8d03adf22: 'Transformer en mosaic?' # Transformer en mosaic?
    dedf661a-8a21-436a-aa80-5799865cf897: Titre # Titre
    e11e6137-c5b2-486e-90d1-c511e55f986f: Texte # Texte
    e62f2e15-68f6-48d6-94ea-945bcf3e9311: Texte # Texte
    e1367e57-dd91-4b37-800c-78f7dc738860: Lien # Lien
    eafc472d-c76f-4a79-a9f2-55fba89aa065: 'Contenu flexible' # Contenu flexible
    ee5544e3-9a58-4e7f-8a6b-8139a835c792: Lien # Lien
    f6c79504-6238-4159-acab-af1e951cff91: Lien # Lien
    fc2cb4bb-e016-46f9-a830-653496da88d7: Français # Français
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  switcher:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: $CRAFT_SYSTEM_STATUS
  name: $CRAFT_SYSTEM_NAME
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: America/Toronto
